/**
 * Core ESLint rules (correctness, safety, and style kept despite Prettier).
 * Formatting handled by Prettier + eslint-config-prettier is not listed here.
 */
module.exports = {
  // correctness / safety
  'constructor-super': 'error',
  curly: ['error', 'multi-line'],
  'default-case-last': 'error',
  'dot-notation': ['error', { allowKeywords: true }],
  eqeqeq: ['error', 'always', { null: 'ignore' }],
  'getter-return': 'error',
  'no-array-constructor': 'error',
  'no-caller': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': 'error',
  'no-const-assign': 'error',
  'no-constant-condition': 'error',
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-dupe-args': 'error',
  'no-dupe-class-members': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-empty-character-class': 'error',
  'no-empty-pattern': 'error',
  'no-eval': 'error',
  'no-ex-assign': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-boolean-cast': 'error',
  'no-fallthrough': 'error',
  'no-func-assign': 'error',
  'no-global-assign': 'error',
  'no-implied-eval': 'error',
  'no-import-assign': 'error',
  'no-invalid-regexp': 'error',
  'no-irregular-whitespace': 'error',
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
  'no-lone-blocks': 'error',
  'no-loss-of-precision': 'error',
  'no-misleading-character-class': 'error',
  'no-mixed-operators': [
    'error',
    {
      groups: [
        ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
        ['&&', '||'],
        ['in', 'instanceof'],
      ],
      allowSamePrecedence: true,
    },
  ],
  'no-multi-str': 'error',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-object': 'error',
  'no-new-symbol': 'error',
  'no-new-wrappers': 'error',
  'no-obj-calls': 'error',
  'no-octal': 'error',
  'no-octal-escape': 'error',
  'no-proto': 'error',
  'no-prototype-builtins': 'error',
  'no-redeclare': ['error', { builtinGlobals: true }],
  'no-regex-spaces': 'error',
  'no-self-assign': ['error', { props: true }],
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'error',
  'no-template-curly-in-string': 'error',
  'no-this-before-super': 'error',
  'no-throw-literal': 'error',
  'no-unexpected-multiline': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unneeded-ternary': ['error', { defaultAssignment: false }],
  'no-unreachable': 'error',
  'no-unreachable-loop': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'no-unused-expressions': ['error', { allowShortCircuit: true, allowTernary: true, allowTaggedTemplates: true }],
  'no-unused-vars': ['error', { vars: 'all', args: 'after-used', ignoreRestSiblings: true }],
  'no-use-before-define': ['error', { functions: false, classes: false, variables: false }],
  'no-useless-backreference': 'error',
  'no-useless-call': 'error',
  'no-useless-catch': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-constructor': 'error',
  'no-useless-escape': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-with': 'error',
  'object-shorthand': ['error', 'always', { avoidQuotes: true }],
  'one-var': ['error', { initialized: 'never' }],
  'prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: true }],
  'prefer-promise-reject-errors': 'off',
  'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
  'symbol-description': 'error',
  'unicode-bom': ['error', 'never'],
  'use-isnan': 'error',
  'valid-typeof': 'error',
  yoda: ['error', 'never'],

  // style kept despite Prettier
  camelcase: ['error', { properties: 'never', ignoreDestructuring: true }],
  'func-style': ['error', 'expression', { allowArrowFunctions: true }],
  'new-cap': ['error', { capIsNew: false }],
  'no-return-assign': ['error', 'except-parens'],
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'spaced-comment': ['error', 'always', { line: { markers: ['*package'] }, block: { balanced: true } }],

  // disabled: handled by Prettier
  indent: 'off',
  quotes: 'off',
  semi: 'off',
  'comma-dangle': 'off',
  'comma-spacing': 'off',
  'comma-style': 'off',
  'key-spacing': 'off',
  'keyword-spacing': 'off',
  'space-before-blocks': 'off',
  'space-before-function-paren': 'off',
  'space-in-parens': 'off',
  'space-infix-ops': 'off',
  'arrow-spacing': 'off',
  'brace-style': 'off',
  'eol-last': 'off',
  'no-trailing-spaces': 'off',
  'no-multiple-empty-lines': 'off',
  'object-curly-spacing': 'off',
  'array-bracket-spacing': 'off',
  'template-curly-spacing': 'off',
  'generator-star-spacing': 'off',
  'yield-star-spacing': 'off',
  'no-extra-parens': 'off',
  'no-floating-decimal': 'off',
  'no-multi-spaces': 'off',
  'no-whitespace-before-property': 'off',
  'operator-linebreak': 'off',
  'quote-props': 'off',
  'rest-spread-spacing': 'off',
  'semi-spacing': 'off',
  'space-unary-ops': 'off',
  'switch-colon-spacing': 'off',
  'template-tag-spacing': 'off',
  'wrap-iife': 'off',
  'wrap-regex': 'off',
}
